export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

export const LOADING_POSTS = "LOADING_POSTS";
export const LOAD_ALL_POSTS = "LOAD_ALL_POSTS";
export const LOAD_MY_POSTS = "LOAD_MY_POSTS";
export const LOAD_USER_POSTS = "LOAD_USER_POSTS";
export const ADD_POST = "ADD_POST";
export const TOGGLE_LIKE_UNLIKE_POST = "TOGGLE_LIKE_UNLIKE_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_POST = "DELETE_POST";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const UPDATE_PROFILE_PHOTO = "UPDATE_PROFILE_PHOTO";

// SEPARATE ERROR FOR UI
